### ISSUE TITLE
Support for Becker-Hickl .sdt file format 

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#143]
### Background info
The *.sdt Becker-Hickl file format is quite common for time-correlated single photon counting ([TCSPC](https://en.wikipedia.org/wiki/Fluorescence-lifetime_imaging_microscopy#TCSPC)) setups. It is used both in a microscopy settings, in fluorescence lifetime imaging microscopy (FLIM) data aqusition, as well as measuring regular time-gated fluorescence decays (at multiple wavelengths using a monochromator). Support for the proprietary sdt file format would need to cover both use cases, so a collection of issues is identified.

The company has a very extensive Handbook online in which most information can be found:
https://www.becker-hickl.com/handbookphp.htm   

### Dependent issues / tasks
Reading raw data:
- [ ] #124 get a reader for *.sdt files
Reading FLIM data:
- [ ] #142  Support for FLIM ascii data format 
- [ ] # Support reading sdt as FLIM data
Reading TCSPC data:
- [ ] #144 Support reading sdt as TCSPC data
